# Generated by Django 4.0.5 on 2024-07-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Indexing Officer', 'Indexing Officer'), ('Indexing Unit', 'Indexing Unit'), ('Registrar', 'Registrar'), ('Registration', 'Registration'), ('Sysadmin', 'Sysadmin')], default='Student', max_length=20),
        ),
    ]
