# Generated by Django 4.0.5 on 2024-07-07 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueIndexing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_no', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True)),
                ('index_number', models.CharField(max_length=200, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.academicsession')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='issue_indexing', to='institutions.institutionprofile')),
                ('student_indexing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.studentindexing')),
                ('student_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.studentprofile')),
            ],
            options={
                'unique_together': {('matric_no', 'index_number')},
            },
        ),
    ]
