# Generated by Django 4.0.5 on 2024-08-05 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexing_unit', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='issueindexing',
            unique_together=set(),
        ),
    ]
