# Generated by Django 4.0.5 on 2025-11-12 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0012_alter_indexingpayment_institution_and_more'),
        ('indexing_unit', '0002_alter_issueindexing_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueindexing',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_indexing', to='institutions.institutionprofile'),
        ),
    ]
