# Generated by Django 4.0.5 on 2023-06-09 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admissionquota',
            old_name='admission_quota_1',
            new_name='admission_quota',
        ),
        migrations.RemoveField(
            model_name='admissionquota',
            name='admission_quota_2',
        ),
        migrations.RemoveField(
            model_name='admissionquota',
            name='course_1',
        ),
        migrations.RemoveField(
            model_name='admissionquota',
            name='course_2',
        ),
    ]
