# Generated by Django 4.0.5 on 2024-04-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionquota',
            name='admission_quota',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
