# Generated by Django 4.0.5 on 2023-06-17 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionprofile',
            name='accreditation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 17, 16, 12, 47, 648534)),
        ),
    ]
