# Generated by Django 4.0.5 on 2023-06-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_alter_institutionprofile_accreditation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionprofile',
            name='accreditation_date',
            field=models.DateField(null=True),
        ),
    ]
