# Generated by Django 4.0.5 on 2024-07-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_alter_studentindexing_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentindexing',
            name='indexing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('board_rejection', 'Board Rejection'), ('indexed', 'Indexed')], default='pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentindexing',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=200),
        ),
    ]
