# Generated by Django 4.0.5 on 2024-07-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_alter_studentindexing_indexing_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentindexing',
            name='rejection_status',
            field=models.IntegerField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending'),
        ),
        migrations.AlterField(
            model_name='studentindexing',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=200),
        ),
    ]
