# Generated by Django 4.0.5 on 2024-07-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_alter_studentindexing_rejection_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentindexing',
            name='rejection_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=200),
        ),
    ]
