# Generated by Django 4.0.5 on 2024-08-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_alter_studentindexing_rejection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
