# Generated by Django 4.0.5 on 2024-08-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0006_academicsession_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicsession',
            name='active',
        ),
        migrations.AddField(
            model_name='admissionquota',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
