# Generated by Django 4.0.5 on 2023-07-16 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0006_institutionprofile_accreditation_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='academic_session',
            field=models.CharField(blank=True, choices=[('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026'), ('2026/2027', '2026/2027'), ('2027/2028', '2027/2028'), ('2028/2029', '2028/2029'), ('2029/2030', '2029/2030'), ('2030/2031', '2030/2031'), ('2031/2032', '2031/2032'), ('2032/2033', '2032/2033'), ('2033/2034', '2033/2034'), ('2034/2035', '2034/2035')], max_length=100),
        ),
        migrations.AddField(
            model_name='academicsession',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.institutionprofile'),
        ),
        migrations.AlterField(
            model_name='degreeresults',
            name='student_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.studentprofile'),
        ),
        migrations.AlterField(
            model_name='gcealevels',
            name='student_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.studentprofile'),
        ),
        migrations.AlterField(
            model_name='indexingpayment',
            name='student_indexing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.studentindexing'),
        ),
        migrations.AlterField(
            model_name='indexingpayment',
            name='student_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.studentprofile'),
        ),
        migrations.AlterField(
            model_name='studentindexing',
            name='student_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.studentprofile'),
        ),
        migrations.AlterField(
            model_name='utmegrade',
            name='student_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.studentprofile'),
        ),
    ]
