# Generated by Django 4.0.5 on 2023-07-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0007_academicsession_academic_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='academic_session',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
