# Generated by Django 4.0.5 on 2024-05-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0008_alter_institutionprofile_institution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreeresults',
            name='admission_letter',
            field=models.FileField(default=1, upload_to='%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gcealevels',
            name='admission_letter',
            field=models.FileField(default=1, upload_to='%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='lga_identification',
            field=models.FileField(default=1, upload_to='%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='passport_photo',
            field=models.FileField(default=1, upload_to='%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfergrade',
            name='admission_letter',
            field=models.FileField(default=1, upload_to='%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utmegrade',
            name='admission_letter',
            field=models.FileField(default=1, upload_to='%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
