# Generated by Django 4.0.5 on 2024-08-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0008_remove_admissionquota_active_admissionquota_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
