# Generated by Django 4.0.5 on 2024-08-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0009_academicsession_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeresults',
            name='institution',
            field=models.CharField(choices=[('University of Nigeria', 'University of Nigeria'), ('Nnamdi Azikiwe University', 'Nnamdi Azikiwe University'), ('University of Maiduguri', 'University of Maiduguri'), ('Ahmadu Bello University Zaria', 'Ahmadu Bello University Zaria'), ('University of Uyo', 'University of Uyo'), ('University of Calabar', 'University of Calabar'), ('Bayero University Kano', 'Bayero University Kano'), ('University of Lagos', 'University of Lagos'), ('Usman Danfodio University', 'Usman Danfodio University'), ('Federal University Dutsinma Katsina State', 'Federal University Dutsinma Katsina State'), ('Federal University Azare', 'Federal University Azare'), ('David Umahi Federal University of Health Sciences', 'David Umahi Federal University of Health Sciences'), ('Baze University Abuja', 'Baze University Abuja'), ('Lead City University', 'Lead City University'), ('Osun State University', 'Osun State University'), ('Ajayi Crowther University Oyo', 'Ajayi Crowther University Oyo'), ('Gregory University Uturu Abia State', 'Gregory University Uturu Abia State'), ('Bayero University Kano', 'Bayero University Kano'), ('Federal University of Lafia', 'Federal University of Lafia'), ('Pamo University', 'Pamo University'), ('Evangel University, Akaeze', 'Evangel University, Akaeze'), ('X-Ray Tech Delta State', 'X-Ray Tech Delta State'), ('College of Health Technology Calabar', 'College of Health Technology Calabar'), ('College of Health Technology Kano', 'College of Health Technology Kano'), ('Caliphate College of Health', 'Caliphate College of Health'), ('Enugu State College of Health', 'Enugu State College of Health'), ('Plateau State College of Health', 'Plateau State College of Health'), ('Plateau State College of Health Zawan', 'Plateau State College of Health Zawan'), ('Shehu Idris College of Health', 'Shehu Idris College of Health'), ('Lafia School of Health', 'Lafia School of Health'), ('Ekiti State College of Health', 'Ekiti State College of Health'), ('Taraba State College of Health', 'Taraba State College of Health'), ('Ogun State Polythecnic of Health', 'Ogun State Polythecnic of Health'), ('Nasarawa State College of Health', 'Nasarawa State College of Health'), ('Collage of Health Technology Gwadabawa Sokoto', 'Collage of Health Technology Gwadabawa Sokoto'), ('Millennium College of Health Technology Akure', 'Millennium College of Health Technology Akure')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentindexing',
            name='rejection_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('indexed', 'Indexed')], default='pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentindexing',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('indexed', 'Indexed')], default='pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='state_of_origin',
            field=models.CharField(blank=True, choices=[('Abia', 'Abia'), ('Adamawa', 'Adamawa'), ('Akwa Ibom', 'Akwa Ibom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Enugu', 'Enugu'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('FCT', 'FCT'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Katsina', 'Katsina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transfergrade',
            name='institution',
            field=models.CharField(choices=[('University of Nigeria', 'University of Nigeria'), ('Nnamdi Azikiwe University', 'Nnamdi Azikiwe University'), ('University of Maiduguri', 'University of Maiduguri'), ('Ahmadu Bello University Zaria', 'Ahmadu Bello University Zaria'), ('University of Uyo', 'University of Uyo'), ('University of Calabar', 'University of Calabar'), ('Bayero University Kano', 'Bayero University Kano'), ('University of Lagos', 'University of Lagos'), ('Usman Danfodio University', 'Usman Danfodio University'), ('Federal University Dutsinma Katsina State', 'Federal University Dutsinma Katsina State'), ('Federal University Azare', 'Federal University Azare'), ('David Umahi Federal University of Health Sciences', 'David Umahi Federal University of Health Sciences'), ('Baze University Abuja', 'Baze University Abuja'), ('Lead City University', 'Lead City University'), ('Osun State University', 'Osun State University'), ('Ajayi Crowther University Oyo', 'Ajayi Crowther University Oyo'), ('Gregory University Uturu Abia State', 'Gregory University Uturu Abia State'), ('Bayero University Kano', 'Bayero University Kano'), ('Federal University of Lafia', 'Federal University of Lafia'), ('Pamo University', 'Pamo University'), ('Evangel University, Akaeze', 'Evangel University, Akaeze'), ('X-Ray Tech Delta State', 'X-Ray Tech Delta State'), ('College of Health Technology Calabar', 'College of Health Technology Calabar'), ('College of Health Technology Kano', 'College of Health Technology Kano'), ('Caliphate College of Health', 'Caliphate College of Health'), ('Enugu State College of Health', 'Enugu State College of Health'), ('Plateau State College of Health', 'Plateau State College of Health'), ('Plateau State College of Health Zawan', 'Plateau State College of Health Zawan'), ('Shehu Idris College of Health', 'Shehu Idris College of Health'), ('Lafia School of Health', 'Lafia School of Health'), ('Ekiti State College of Health', 'Ekiti State College of Health'), ('Taraba State College of Health', 'Taraba State College of Health'), ('Ogun State Polythecnic of Health', 'Ogun State Polythecnic of Health'), ('Nasarawa State College of Health', 'Nasarawa State College of Health'), ('Collage of Health Technology Gwadabawa Sokoto', 'Collage of Health Technology Gwadabawa Sokoto'), ('Millennium College of Health Technology Akure', 'Millennium College of Health Technology Akure')], max_length=200, null=True),
        ),
    ]
