# Generated by Django 4.0.5 on 2024-05-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0009_degreeresults_admission_letter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degreeresults',
            name='admission_letter',
        ),
        migrations.RemoveField(
            model_name='gcealevels',
            name='admission_letter',
        ),
        migrations.RemoveField(
            model_name='transfergrade',
            name='admission_letter',
        ),
        migrations.RemoveField(
            model_name='utmegrade',
            name='admission_letter',
        ),
        migrations.AddField(
            model_name='studentindexing',
            name='admission_letter',
            field=models.FileField(default=1, upload_to='%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
