# Generated by Django 4.0.5 on 2024-05-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0011_alter_studentindexing_degree_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentindexing',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
