# Generated by Django 4.0.5 on 2025-11-12 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0011_alter_admissionquota_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexingpayment',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institutionprofile'),
        ),
        migrations.AlterField(
            model_name='institutionindexing',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institutionprofile'),
        ),
        migrations.AlterField(
            model_name='studentindexing',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institutionprofile'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institutionprofile'),
        ),
    ]
