# Generated by Django 4.0.5 on 2024-05-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0012_studentindexing_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentindexing',
            name='rejection_status',
            field=models.IntegerField(default=1),
        ),
    ]
